export const LOADING_CONFESS = 'LOADING_CONFESS'
export const LOADING_CONFESS_SUCCESS = 'LOADING_CONFESS_SUCCESS'
export const LOADING_CONFESS_ERROR = 'LOADING_CONFESS_ERROR'

export const POSTING_CONFESS = 'POSTING_CONFESS';
export const POSTING_CONFESS_SUCCESS = 'POSTING_CONFESS_SUCCESS';
export const POSTING_CONFESS_ERROR = 'POSTING_CONFESS_ERROR';

export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const LOADING_COMMENTS_SUCCESS = 'LOADING_COMMENTS_SUCCESS';
export const LOADING_COMMENTS_ERROR = 'LOADING_COMMENTS_ERROR';

export const POSTING_COMMENTS = 'POSTING_COMMENTS';
export const POSTING_COMMENTS_SUCCESS = 'POSTING_COMMENTS_SUCCESS';
export const POSTING_COMMENTS_ERROR = 'POSTING_COMMENTS_ERROR';

export const LOADING_REPLIES = 'LOADING_REPLIES';
export const LOADING_REPLIES_SUCCESS = 'LOADING_REPLIES_SUCCESS';
export const LOADING_REPLIES_ERROR = 'LOADING_REPLIES_ERROR';

export const POSTING_REPLIES = 'POSTING_REPLIES';
export const POSTING_REPLIES_SUCCESS = 'POSTING_REPLIES_SUCCESS';
export const POSTING_REPLIES_ERROR = 'POSTING_REPLIES_ERROR';

export const UPDATING_CONFESS = 'UPDATING_CONFESS';
export const UPDATING_CONFESS_SUCCESS = 'UPDATING_CONFESS_SUCCESS';
export const UPDATING_CONFESS_ERROR = 'UPDATING_CONFESS_ERROR';

export const UPDATING_COMMENT = 'UPDATING_COMMENT';
export const UPDATING_COMMENT_SUCCESS = 'UPDATING_COMMENT_SUCCESS';
export const UPDATING_COMMENT_ERROR = 'UPDATING_COMMENT_ERROR';

export const UPDATING_REPLY = 'UPDATING_REPLY';
export const UPDATING_REPLY_SUCCESS = 'UPDATING_REPLY_SUCCESS';
export const UPDATING_REPLY_ERROR = 'UPDATING_REPLY_ERROR';